### ISSUE TITLE
quality options?

### ISSUE THREAD

**Issue by patrikpatrik** [jaxry/panorama-to-cubemap#8]
Hello Lucas,

Thank you for this great cubemap conversion tool it's very handy. I don't mean to sound repetitive but is it possible to increase the resolution size instead of 1024? I would love 2048 or even better 4096 pixels if it's not too much trouble! Anyway, thanks again!

Cheers~
Patrikpatrik

**Comment by jaxry** [comment]
Hi Patrik,

The size of the output cubemap is dynamic and depends on the size of the input panorama. For a 2048x2048 cubemap image, you'll need to supply a equirectangular input image of 8192x4096 pixels.

**Comment by patrikpatrik** [comment]
Okay got it thank you!
